name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore AlexAssist.UI/AlexAssist.UI.csproj
    
    - name: Build Single File
      run: |
        dotnet publish AlexAssist.UI/AlexAssist.UI.csproj `
          -c Release `
          -r win-x64 `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:EnableCompressionInSingleFile=true `
          /p:IncludeNativeLibrariesForSelfExtract=true `
          /p:DebugType=None `
          /p:DebugSymbols=false
    
    - name: Copy Single Executable
      run: |
        Copy-Item AlexAssist.UI/bin/Release/net8.0-windows/win-x64/publish/AlexAssist.UI.exe AlexAssist.exe
    
    - name: Zip Release
      run: Compress-Archive -Path AlexAssist.UI/bin/Release/net8.0-windows/win-x64/publish/* -DestinationPath AlexAssist.zip
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AlexAssist.exe
          AlexAssist.zip
        name: Release ${{ github.ref_name }}
        body: |
          AlexAssist Release ${{ github.ref_name }}
          
          ## Download Options
          - **AlexAssist.exe**: Single-file executable with everything included
          - **AlexAssist.zip**: Full package with all files extracted
          
          ## Installation
          ### Option 1 (Recommended)
          - Download AlexAssist.exe
          - Run it directly - no installation needed!
          
          ### Option 2
          1. Download AlexAssist.zip
          2. Extract to any location
          3. Run AlexAssist.UI.exe
          
          ## Features
          - Task Management with priorities and categories
          - Personal Diary with code snippet support
          - Code Timer with project tracking
          - Dark/Light theme support
          - Beautiful Material Design UI
          
          ## Notes
          - Data is stored in %AppData%\AlexAssist\
          - Settings can be backed up/restored from the Settings page 